### ISSUE TITLE
Any plan for `:export`?

### ISSUE THREAD

**Issue by baktiaditya** [jimkyndemeyer/react-css-modules-intellij-plugin#3]

**Comment by jimkyndemeyer** [comment]
Hi Bakti.

I'd like to keep this plugin focused on the integration between React and CSS Modules.

What's your use case? Based on https://github.com/css-modules/icss#export it appears that `:export` is implemented by the relevant CSS loader, such as webpack's CSS loader, and not an explicit concern for developers who are styling React components.
